#!/usr/bin/env bash
# A script to display information about my domain names

# define funtion to output subdomain, record type and destination IP
# expects 2 arguments

display_info () {
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' \
	| tail -1 | sed -r "s/$2.$1./$2/g" | \
	awk '{print "The subdomain " $1 " is a " $4 " record and points to " $5}'
	 
}


# control logic to make sure there is at least 1 argument before
# displaying details

if [ "$#" -eq 1 ]
then
	display_info $1 "www"
	display_info $1 "lb-01"
	display_info $1 "web-01"
	display_info $1 "web-02"
elif [ "$#" -eq 2 ]
then
	display_info $1 $2
fi
