#!/usr/bin/env bash
# install and configure nginx

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start && sudo service nginx restart
