#!/usr/bin/env bash
# script that configures my webservers

sudo apt-get update
sudo apt-get install -y nginx

declare place="SSL configuration\n\tadd_header X-Served-By \$HOSTNAME;\n"

sudo sed -i "s/SSL configuration/$place/g" /etc/nginx/sites-available/default

sudo service nginx restart
