#!/usr/bin/env bash
# install and configure HAProxy

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6


sudo apt-get install -y haproxy=2.6.\*

echo "
frontend myfrontend
        bind *:80
        default_backend myservers
backend myservers
        balance roundrobin
        server 156921-web-01 100.25.200.1 check
        server 156921-web-02 18.234.107.65 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart

